#!/usr/bin/env python3
"""Build Shopify THEME files for the Malone LP from the standalone page.

Why a theme template instead of a page-body paste: the page editor's sanitizer strips <script>,
and theme CSS leaks into pasted HTML. A custom layout + template renders our page 1:1, keeps
Shopify's own head scripts/pixels/app embeds via {{ content_for_header }}, and skips the theme
header/footer entirely (no chrome-hide hacks needed).

Output (shopify/theme/):
  layout/malone.liquid            - our <head> + content_for_header, body = content_for_layout + our JS
  templates/page.malone-lp.liquid    - {% layout 'malone' %} + the page body; shows as template "malone"
  assets/pp-malone.css.liquid     - style.css with font URLs via asset_url
  assets/pp-malone.js             - script.js + popup/chat-widget overlay guard
  assets/pp-malone-*              - images, video, fonts (flat names; asset_url needs flat files)

Push (adds files only, never touches existing theme files):
  shopify theme push --store modernaspectshop.myshopify.com --live --allow-live \
    --path shopify/theme --only 'layout/malone.liquid' --only 'templates/page.malone-lp.liquid' --only 'assets/pp-malone*'
"""
import os, re, shutil, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "shopify" / "theme"
html = (ROOT / "index.html").read_text()
css = (ROOT / "assets" / "style.css").read_text()
js = (ROOT / "assets" / "script.js").read_text()

def flat(rel):  # assets/img/hero-mobile.webp -> pp-malone-img-hero-mobile.webp
    return "pp-malone-" + rel[len("assets/"):].replace("/", "-")

def liquid_url(rel):
    return "{{ '" + flat(rel) + "' | asset_url }}"

# ---------------------------------------------------------------- assets
for d in ["layout", "templates", "assets"]:
    (OUT / d).mkdir(parents=True, exist_ok=True)
for old in OUT.glob("assets/pp-malone-*"):
    old.unlink()
copied = []
for sub in sorted(p.name for p in (ROOT / "assets").iterdir() if p.is_dir()):
    for f in sorted((ROOT / "assets" / sub).iterdir()):
        if f.is_file():
            rel = f"assets/{sub}/{f.name}"
            shutil.copy2(f, OUT / "assets" / flat(rel))
            copied.append(flat(rel))
for f in sorted((ROOT / "assets").iterdir()):  # root-level assets (e.g. the white logo svg); css/js are built separately
    if f.is_file() and f.suffix not in (".css", ".js"):
        rel = f"assets/{f.name}"; shutil.copy2(f, OUT / "assets" / flat(rel)); copied.append(flat(rel))

ASSET_RE = re.compile(r"""(["'(])(assets/[^"')\s]+)""")
def rewrite(txt):
    return ASSET_RE.sub(lambda m: m.group(1) + liquid_url(m.group(2)), txt)

# ---------------------------------------------------------------- head
head = html.split("<head>", 1)[1].split("</head>", 1)[0]
head = head.replace('<link rel="stylesheet" href="assets/style.css">',
                    "<link rel=\"stylesheet\" href=\"{{ 'pp-malone.css' | asset_url }}\">")
head = re.sub(r'<link rel="canonical" href="[^"]*">', '<link rel="canonical" href="{{ canonical_url }}">', head)
head = re.sub(r'\n?<meta name="robots"[^>]*>', '', head)  # preview-only noindex must never reach the store
head = re.sub(r'<meta property="og:url" content="[^"]*">', '<meta property="og:url" content="{{ canonical_url }}">', head)
head = head.replace("https://ksimmons0420.github.io/postandporch-malone-lp/assets/img/og-image.jpg",
                    "{{ 'pp-malone-img-og-image.jpg' | asset_url }}")
head = rewrite(head)
assert "ksimmons0420" not in head, "GitHub URL left in head"
head = head.rstrip() + "\n<!-- Osano cookie consent: same tag the store theme loads in theme.liquid, so consent behaves identically on this page -->\n<script src=\"https://cmp.osano.com/kCUuC20G3H/2972046d-16cf-42d0-ad27-37d36311c2f5/osano.js\"></script>\n{{ content_for_header }}\n"

layout = "<!DOCTYPE html>\n<html lang=\"{{ request.locale.iso_code }}\">\n<head>" + head + "</head>\n" \
         "<body class=\"template-page-malone\">\n{{ content_for_layout }}\n" \
         "<script src=\"{{ 'pp-malone.js' | asset_url }}\" defer></script>\n</body>\n</html>\n"
(OUT / "layout" / "malone.liquid").write_text(layout)

# ---------------------------------------------------------------- template (page body)
body = html.split("<body>", 1)[1].split("</body>", 1)[0]
body = body.replace('<script src="assets/script.js" defer></script>', "")
body = rewrite(body).strip()
left = re.findall(r"assets/[^\"')\s]+", body.replace("| asset_url", "")); assert not left, f"unrewritten asset path in body: {left[:3]}"
template = "{% layout 'malone' %}\n{% comment %} Post & Porch - The Malone LP. Generated by shopify/build_theme.py - edit the standalone page, then rebuild. {% endcomment %}\n" + body + "\n"
(OUT / "templates" / "page.malone-lp.liquid").write_text(template)

# ---------------------------------------------------------------- css
css_l = re.sub(r"url\('fonts/([^']+)'\)", lambda m: "url('{{ \"pp-malone-fonts-" + m.group(1) + "\" | asset_url }}')", css)
css_l += "\n/* Shopify-only: no promo popups on this landing page (owner spec). Toggle by removing this rule. */\n[id^=\"alia-root\"], [id*=\"alia-popup\" i] { display: none !important; visibility: hidden !important; pointer-events: none !important; }\n"
(OUT / "assets" / "pp-malone.css.liquid").write_text(css_l)

# ---------------------------------------------------------------- js (+ overlay guard)
GUARD = r"""
/* ===== Overlay guard (Shopify only): hide third-party popups that app embeds inject on this page.
   The cookie/privacy banner is intentionally NOT suppressed (compliance = client's call). ===== */
(function () {
  var SEL = ['[id*="alia" i]', '[class*="alia-" i]', '[class*="klaviyo-form" i][role="dialog"]', '[id*="privy" i]', '[class*="popup" i][class*="modal" i]'];
  var sticky = document.querySelector('.sticky-cta, .sticky-bar, [data-sticky-cta]');
  var suppressed = false;
  function hide(el) { if (!el || el === sticky || (sticky && sticky.contains(el))) return; suppressed = true; if (/^alia-root/.test(el.id)) { el.remove(); return; } el.style.setProperty('display', 'none', 'important'); }
  /* Popups lock page scroll (Alia sets body.style.overflow=hidden on mount). Once we suppress one, its unlock never runs — release it ourselves. */
  function unlock() {
    if (!suppressed) return;
    [document.body, document.documentElement].forEach(function (el) {
      var st = el.style;
      if (/hidden/.test(st.overflow)) st.removeProperty('overflow');
      if (/hidden/.test(st.overflowY)) st.removeProperty('overflow-y');
      if (st.position === 'fixed') { st.removeProperty('position'); st.removeProperty('top'); st.removeProperty('width'); }
    });
  }
  function sweep() {
    SEL.forEach(function (s) { try { document.querySelectorAll(s).forEach(hide); } catch (e) {} });
    var vw = window.innerWidth, vh = window.innerHeight;
    document.querySelectorAll('body > *, body > * > *').forEach(function (el) {
      if (el === sticky || (sticky && sticky.contains(el)) || el.tagName === 'MAIN' || el.tagName === 'HEADER' || el.tagName === 'FOOTER') return;
      var cs = getComputedStyle(el); if (cs.position !== 'fixed') return;
      var r = el.getBoundingClientRect(); if (!r.width || !r.height) return;
      var z = parseInt(cs.zIndex, 10) || 0;
      if (z >= 1000 && r.width * r.height >= vw * vh * 0.25 && !/privacy|consent|cookie|shopify-pc/i.test(el.id + ' ' + el.className)) hide(el);
    });
    unlock();
  }
  sweep();
  /* Permanent, coalesced per frame: the CSS hide rule is permanent, so a late (timed/exit-intent) popup must also get its scroll-lock released. */
  var queued = false;
  function schedule() { if (queued) return; queued = true; requestAnimationFrame(function () { queued = false; sweep(); }); }
  var mo = new MutationObserver(schedule);
  mo.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['style', 'class'] });
  mo.observe(document.documentElement, { attributes: true, attributeFilter: ['style'] });
})();
"""
(OUT / "assets" / "pp-malone.js").write_text(js.rstrip() + "\n" + GUARD)

print(f"theme built -> {OUT}")
print(f"  assets copied: {len(copied)}")
print(f"  layout {len(layout):,} B | template {len(template):,} B | css {len(css_l):,} B | js {len(js)+len(GUARD):,} B")
